version: '3.9'
services:
  eureka-server:
    build:
      context: ./hr-eureka-server
    ports:
      - "8761:8761"
  api-gatway-service:
    build:
      context: ./netflix-zuul-api-gateway-server
    expose:
      - "8765"
    ports:
      - "8080:8765"
  hr-payroll-service:
    build:
      context: ./hr-payroll
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  hr-worker-service:
    build:
      context: ./hr-worker
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
